# Introduction to Julia, part 2

<img src="./images/julia_logo.png" align="center" width="400"/>

https://julialang.org

## Matrices and vectors

### Dimensions

In [2]:
x = randn(5, 3)

5×3 Matrix{Float64}:
  0.915491  -0.230816  -1.74359
 -0.470961  -0.371227   0.22421
  0.948704  -0.36817   -2.42639
  0.450668  -0.674163   0.717575
 -0.576843   0.984813  -0.00227637

In [3]:
size(x)

(5, 3)

In [4]:
size(x, 1) # nrow() in R

5

In [5]:
size(x, 2) # ncol() in R

3

In [6]:
# total number of elements
length(x)

15

In [7]:
# "dims" argument for function applied to arrays
sum(x, dims=1)

1×3 Matrix{Float64}:
 1.26706  -0.659563  -3.23047

In [8]:
sum(x, dims=2)

5×1 Matrix{Float64}:
 -1.0589138372716314
 -0.6179776258434972
 -1.8458532038985327
  0.49408004733523364
  0.4056940579520651

In [9]:
sum(x, dims=[1,2])

1×1 Matrix{Float64}:
 -2.622970561726363

In [10]:
sort(x, dims=1)

5×3 Matrix{Float64}:
 -0.576843  -0.674163  -2.42639
 -0.470961  -0.371227  -1.74359
  0.450668  -0.36817   -0.00227637
  0.915491  -0.230816   0.22421
  0.948704   0.984813   0.717575

In [11]:
sort(x, dims=2)

5×3 Matrix{Float64}:
 -1.74359   -0.230816    0.915491
 -0.470961  -0.371227    0.22421
 -2.42639   -0.36817     0.948704
 -0.674163   0.450668    0.717575
 -0.576843  -0.00227637  0.984813

### Indexing

In [12]:
# 5 × 5 matrix of random Normal(0, 1)
x = randn(5, 5)

5×5 Matrix{Float64}:
 -0.117188  -0.993886  -0.273581  -0.0654043   2.68592
 -1.05477    1.07551   -1.0214     1.5579     -1.80041
  0.240365  -0.190682   1.60163   -1.13262     0.557946
  0.566238   0.464624   0.385242  -0.463516    0.32635
 -0.578983   0.901238   0.95375   -0.315408   -0.65493

In [13]:
# first column
x[:, 1]

5-element Vector{Float64}:
 -0.11718815714536887
 -1.0547658783228009
  0.24036498735432768
  0.5662383435587747
 -0.5789825705135948

In [14]:
# first row ( but still shown as column vector)
x[1, :]

5-element Vector{Float64}:
 -0.11718815714536887
 -0.9938859024958031
 -0.27358067781758444
 -0.0654042774000804
  2.685922880322422

In [15]:
# sub-array
# Note : creates a copy, which brings about a new memory allocation
zz = x[1:2, 2:3]

2×2 Matrix{Float64}:
 -0.993886  -0.273581
  1.07551   -1.0214

In [16]:
typeof(zz)

Matrix{Float64} (alias for Array{Float64, 2})

In [17]:
zz[2, 1] = 0.0
x
# change in zz does not change x

5×5 Matrix{Float64}:
 -0.117188  -0.993886  -0.273581  -0.0654043   2.68592
 -1.05477    1.07551   -1.0214     1.5579     -1.80041
  0.240365  -0.190682   1.60163   -1.13262     0.557946
  0.566238   0.464624   0.385242  -0.463516    0.32635
 -0.578983   0.901238   0.95375   -0.315408   -0.65493

In [18]:
# getting a subset of a matrix creates a copy, but you can also create "views"
# Note : This does not require a new memory allocation 
z = view(x, 1:2, 2:3)

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
 -0.993886  -0.273581
  1.07551   -1.0214

In [19]:
typeof(z)

SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}

In [20]:
# same as
@views z = x[1:2, 2:3]

2×2 view(::Matrix{Float64}, 1:2, 2:3) with eltype Float64:
 -0.993886  -0.273581
  1.07551   -1.0214

In [21]:
# change in z changes x as well
z[2, 2] = 0.0
x

5×5 Matrix{Float64}:
 -0.117188  -0.993886  -0.273581  -0.0654043   2.68592
 -1.05477    1.07551    0.0        1.5579     -1.80041
  0.240365  -0.190682   1.60163   -1.13262     0.557946
  0.566238   0.464624   0.385242  -0.463516    0.32635
 -0.578983   0.901238   0.95375   -0.315408   -0.65493

In [22]:
# y points to same data as x
y = x
# Note : Does a memory allocation occur? Nope. This is for the less use of memory resources. 
# R에서와는 조금 다르게 동작.

5×5 Matrix{Float64}:
 -0.117188  -0.993886  -0.273581  -0.0654043   2.68592
 -1.05477    1.07551    0.0        1.5579     -1.80041
  0.240365  -0.190682   1.60163   -1.13262     0.557946
  0.566238   0.464624   0.385242  -0.463516    0.32635
 -0.578983   0.901238   0.95375   -0.315408   -0.65493

In [23]:
# x and y point to same data
# Note : 'pointer' is a computer memeory address
pointer(x), pointer(y)

(Ptr{Float64} @0x0000000113d272f0, Ptr{Float64} @0x0000000113d272f0)

In [24]:
# changing y also changes x
y[:, 1] .= 0  # Dot broadcasting: "vectorization" in Julia. More below
# `y[:,1]=0` causes an error.
x

5×5 Matrix{Float64}:
 0.0  -0.993886  -0.273581  -0.0654043   2.68592
 0.0   1.07551    0.0        1.5579     -1.80041
 0.0  -0.190682   1.60163   -1.13262     0.557946
 0.0   0.464624   0.385242  -0.463516    0.32635
 0.0   0.901238   0.95375   -0.315408   -0.65493

In [25]:
# create a new copy of data
z = copy(x)

5×5 Matrix{Float64}:
 0.0  -0.993886  -0.273581  -0.0654043   2.68592
 0.0   1.07551    0.0        1.5579     -1.80041
 0.0  -0.190682   1.60163   -1.13262     0.557946
 0.0   0.464624   0.385242  -0.463516    0.32635
 0.0   0.901238   0.95375   -0.315408   -0.65493

In [26]:
pointer(x), pointer(z)  # they should be different now

(Ptr{Float64} @0x0000000113d272f0, Ptr{Float64} @0x0000000113d27e30)

In [27]:
a = 1.0  # Float64
b = a
# copy가 아님. memory allocation 발생 없음
b

1.0

In [28]:
a = 2.0
# a = 2.0 이 a의 내용을 바꾸는 것이 아니라 a를 새롭게 정의하게 된 것임. (Float 1.0은 immuatable value이기 때문)
b

1.0

#### Note about `y = x` expression 
- `x = ...` does not brings out any memory allocation. It is just a 'naming'.

```julia
x = randn(5,3)
y = x
x = randn(5,3)
y = x
```

- Let's observe what is going on in the codes above.
    - `x = randn(5,3)` : allocate memory to a new matrix and then name it "x".
    - `y = x` : now "y" also refers to the matrix which "x" is currently referring to. (not brings out any memory allocation)
    - `x = randn(5,3)` : allocate memory to a new matrix and then name it "x". In this process, the binding between the variable name "x" and the matrix generated in the first line is broken. But still, "y" refers to the original matrix so that "x" and "y" are different now. 
    - `y = x` : as in the second line, now "y" also refers to the matrix which "x" is currently referring to. (not brings out any memory allocation) In this process, the binding between the variable name "y" and the matrix generated in the first line is broken. 
    - After all this codes are implemented, the matrix generated in the first line is not referred by any variable name. It becomes a "garbage" object. Julia operates a cleaner to remove such objects.
- What about in R language?
    - In R, `y = x` or equivalently, `y <- x` creates a copy only when it is necessary.
    - Observe the code `x = matrix(rnorm(10), ncol=2)  ;  y <- x  ;  y[1,1] <- 0`
    - For `y <-x` , it works same as Julia. No copy occurs, "x" and "y" both refer to same object(matrix).
    - But for `y[1,1]<-0`, copy occurs. "x" and "y" refers to different objects now.
    - In other words, copy is created only if the object has change.

#### What's the difference between `y = x` and `b = a`?

- In Julia, everything is an object (see **Types** below). But there are *mutable* and *immutable* objects.
- In *assignment* of the form `x = ...`, the LHS is a variable name. Assignment changes which object the variable `x` refers to (called a *variable binding*). 
- After the statement `b = a` any change to `a` also affects `b`. However, the value bound to `a` is `1.0`, an immutable value. 
- You can't mutate an immutable object. The next statement `a = 2.0` does *not* mutate the value bound to `a` (`1.0`), but create a new immutable object `2.0` and re-binds it to variable `a`.
- Binding of `b` to the previous object (`1.0`) is not affected. Hence there's no way to tell if it was copied or referenced.

In [29]:
# guess what will happen
x = randn(5, 5)
y

5×5 Matrix{Float64}:
 0.0  -0.993886  -0.273581  -0.0654043   2.68592
 0.0   1.07551    0.0        1.5579     -1.80041
 0.0  -0.190682   1.60163   -1.13262     0.557946
 0.0   0.464624   0.385242  -0.463516    0.32635
 0.0   0.901238   0.95375   -0.315408   -0.65493

- On the other hand, `Array` is a mutable object.
- `y[:, 1] .= 0` is *not* an assignment, but a *mutation*.
- `x = x .+ 0.1` is an assignment, whereas `x .+= 0.1` is a mutation.

In [30]:
y = x

5×5 Matrix{Float64}:
  0.782523   1.75105   -1.96364    0.463421    1.59847
 -1.06999   -0.590444  -0.437101  -0.830196    1.32644
 -0.75357   -0.763365  -0.544193   0.0732324  -0.358088
 -0.606587   0.309038  -1.1324    -0.676585    1.40927
  0.086041  -0.147394  -1.17742    1.46139     1.99438

In [31]:
x .+= 2
y
# `x .+= 1` (semantically) in-place modification, which saves memory resources.
# This is what R cannot do. On the other hand, C language has this function. 

5×5 Matrix{Float64}:
 2.78252   3.75105  0.0363585  2.46342  3.59847
 0.930008  1.40956  1.5629     1.1698   3.32644
 1.24643   1.23664  1.45581    2.07323  1.64191
 1.39341   2.30904  0.867601   1.32341  3.40927
 2.08604   1.85261  0.822583   3.46139  3.99438

In [32]:
(pointer(x), pointer(y))

(Ptr{Float64} @0x0000000116965010, Ptr{Float64} @0x0000000116965010)

In [33]:
x = x .+ 0.1
# `x = x .+ 1` creates a new object and rename it as x
# This is what R does.
y

5×5 Matrix{Float64}:
 2.78252   3.75105  0.0363585  2.46342  3.59847
 0.930008  1.40956  1.5629     1.1698   3.32644
 1.24643   1.23664  1.45581    2.07323  1.64191
 1.39341   2.30904  0.867601   1.32341  3.40927
 2.08604   1.85261  0.822583   3.46139  3.99438

In [34]:
(pointer(x), pointer(y))

(Ptr{Float64} @0x000000011612b1d0, Ptr{Float64} @0x0000000116965010)

### Concatenate matrices

In [35]:
# 1-by-3 array
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [36]:
# 3-by-1 vector
[1, 2, 3]
# row vector and column vector have different types. row vector is a matrix and column vector is a vector.
# Default for vector is a column vector.

3-element Vector{Int64}:
 1
 2
 3

In [37]:
# Creating a matrix with specified element
A = [1 2 ; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [38]:
# Same as above
B = [1 2
    3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [39]:
C=[ones(Int, 2, 2,) [3;4]
    [5 6] 9]

3×3 Matrix{Int64}:
 1  1  3
 1  1  4
 5  6  9

In [40]:
# multiple assignment by tuple
x, y, z = randn(5, 3), randn(5, 2), randn(3, 5)

([-2.183690985342702 1.1372764457310753 1.7737428432915645; -0.5182647241363008 -0.31196731054127097 1.623965471442824; … ; -1.2475515908073616 -2.1272450846197435 -0.4715367612263856; 0.5892615040610858 -1.9656465811594739 -2.052177950575362], [0.4073451011337501 -0.4886534984570185; 1.665043127702835 0.5598362944902865; … ; 1.3758684156452246 1.4018247537693291; 1.3631496359058977 1.364752282953085], [0.07288442706660046 0.9895543317931201 … -0.4238145829722702 0.5032230989846906; -0.6029362855917739 -0.3298551883709621 … -0.34540504209514344 0.12817286060648775; -0.92732354528771 0.5669070429836237 … 0.395557339474939 0.19796874367999015])

In [41]:
[x y] # 5-by-5 matrix 
# concatenate block matrices

5×5 Matrix{Float64}:
 -2.18369    1.13728    1.77374    0.407345  -0.488653
 -0.518265  -0.311967   1.62397    1.66504    0.559836
  0.801005   0.560637  -0.923666  -1.87624   -0.363445
 -1.24755   -2.12725   -0.471537   1.37587    1.40182
  0.589262  -1.96565   -2.05218    1.36315    1.36475

In [42]:
[x y; z] # 8-by-5 matrix
# This syntax is same as MATLAB

8×5 Matrix{Float64}:
 -2.18369     1.13728    1.77374    0.407345  -0.488653
 -0.518265   -0.311967   1.62397    1.66504    0.559836
  0.801005    0.560637  -0.923666  -1.87624   -0.363445
 -1.24755    -2.12725   -0.471537   1.37587    1.40182
  0.589262   -1.96565   -2.05218    1.36315    1.36475
  0.0728844   0.989554  -1.37758   -0.423815   0.503223
 -0.602936   -0.329855   0.238663  -0.345405   0.128173
 -0.927324    0.566907  -1.42664    0.395557   0.197969

In [43]:
# Other way to concatenate matrices equivalent to `rbind` & `cbind` in R
# reproduce the result in above two cells
hcat(x,y)

5×5 Matrix{Float64}:
 -2.18369    1.13728    1.77374    0.407345  -0.488653
 -0.518265  -0.311967   1.62397    1.66504    0.559836
  0.801005   0.560637  -0.923666  -1.87624   -0.363445
 -1.24755   -2.12725   -0.471537   1.37587    1.40182
  0.589262  -1.96565   -2.05218    1.36315    1.36475

In [44]:
XY=[x y];
vcat(XY, z)

8×5 Matrix{Float64}:
 -2.18369     1.13728    1.77374    0.407345  -0.488653
 -0.518265   -0.311967   1.62397    1.66504    0.559836
  0.801005    0.560637  -0.923666  -1.87624   -0.363445
 -1.24755    -2.12725   -0.471537   1.37587    1.40182
  0.589262   -1.96565   -2.05218    1.36315    1.36475
  0.0728844   0.989554  -1.37758   -0.423815   0.503223
 -0.602936   -0.329855   0.238663  -0.345405   0.128173
 -0.927324    0.566907  -1.42664    0.395557   0.197969

### Dot operation

In Julia, any function `f(x)` can be applied elementwise to an array `X` with the “dot call” syntax `f.(X)`. 

In [45]:
x = randn(5, 3)

5×3 Matrix{Float64}:
 -2.55129    1.63172   -0.168012
  0.124173  -0.375592   0.0495724
  0.498708   0.303592  -0.444669
  0.568302   0.629037  -0.0532919
  2.87703   -1.50145    0.686962

In [46]:
y = 2*ones(5, 3)

5×3 Matrix{Float64}:
 2.0  2.0  2.0
 2.0  2.0  2.0
 2.0  2.0  2.0
 2.0  2.0  2.0
 2.0  2.0  2.0

In [47]:
x .* y # same as x * y in R

5×3 Matrix{Float64}:
 -5.10257    3.26344   -0.336025
  0.248346  -0.751184   0.0991448
  0.997416   0.607185  -0.889338
  1.1366     1.25807   -0.106584
  5.75406   -3.0029     1.37392

In [48]:
x .^ (2) # same as x^(2) in R

5×3 Matrix{Float64}:
 6.50906    2.66251    0.0282282
 0.0154189  0.141069   0.00245742
 0.24871    0.0921683  0.197731
 0.322967   0.395687   0.00284003
 8.2773     2.25434    0.471917

In [49]:
sin.(x)  # same as sin(x) in R
# In Julia, `sin(x)` brings out DimensionMismatch error.

5×3 Matrix{Float64}:
 -0.556616   0.998145  -0.167223
  0.123854  -0.366823   0.0495521
  0.478291   0.29895   -0.430159
  0.538202   0.588366  -0.0532667
  0.261488  -0.997596   0.634192

### Basic linear algebra

In [50]:
x = randn(5)

5-element Vector{Float64}:
  0.6719747304615523
 -0.803468218681417
  1.5111954417300708
 -0.48417571706690976
 -0.44575325448653785

In [51]:
using LinearAlgebra
# vector L2 norm
norm(x)

1.952932402516356

In [52]:
# same as
sqrt(sum(abs2, x))
# `abs2` calculates sqaured absolute value. `sum(f, x)` sums the results of calling function f on each element of x.

1.952932402516356

In [53]:
y = randn(5) # another vector
# dot product
dot(x, y) # x' * y

-0.46955745702360296

In [54]:
# same as
x'y  
# "*" can be ommited in `x'*y` (In Julia, * can be ommited in many cases so that it resembles the mathematical expressions)
# Note that "*" cannot be ommited in `x*y`(Since "xy" can be another variable name)
# "2x" can be done since variable name cannnot begin with a number. "x2" cannot be done.

-0.46955745702360296

In [55]:
x, y = randn(5, 3), randn(3, 2)
# matrix multiplication, same as %*% in R
x * y

5×2 Matrix{Float64}:
  0.426587  -0.368979
  0.397535   0.120602
 -1.82322   -0.150107
  2.28277    0.984875
  0.799095  -0.293572

In [56]:
x = randn(3, 3)

3×3 Matrix{Float64}:
  0.727865   0.199643   0.921103
 -1.52974   -0.146371  -0.272354
 -0.332394  -0.781258  -0.591608

In [57]:
# conjugate transpose (adjoint). For real matrix, it is just a transpose.
x'
# Type is "adjoint". This is because x' does not brings out a new memory allocation. It is just a tagging, as @views.
# Such function is all for saving resources.

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 0.727865  -1.52974   -0.332394
 0.199643  -0.146371  -0.781258
 0.921103  -0.272354  -0.591608

In [58]:
b = rand(3)
x'b # same as x' * b

3-element Vector{Float64}:
 -0.22397464410959755
 -0.42710710227477416
  0.1536824561934808

In [59]:
# trace
tr(x)

-0.010114828012854682

In [60]:
det(x)

0.8015660411377089

In [61]:
rank(x)

3

In [62]:
# Solving linear system Ax=b
A=rand(5,3) ; b=rand(5)
x=A\b
println(norm(A*x-b))
# Ax is not equal to b
# This is because b is not lying on the column space of A
# Then what is the solution x ?

0.5812586049517229


In [63]:
println(norm(A'A*x-A'b))
# x is derived from solving A'Ax=A'b rather than Ax=b

7.447602459741819e-16


In [64]:
# Solving such linear system involves matrix decomposition
X=A'A
CholX=cholesky(X)

Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0247  1.58025    0.941344
  ⋅      0.461776  -0.399247
  ⋅       ⋅         0.443922

### Sparse matrices

In [65]:
using SparseArrays


# 10-by-10 sparse matrix with sparsity level 0.1( maximum nonzero element number is 0.1 * total)
X = sprandn(10, 10, .1)

10×10 SparseMatrixCSC{Float64, Int64} with 11 stored entries:
  ⋅         ⋅    ⋅     ⋅        ⋅       …   ⋅    ⋅     ⋅          ⋅ 
  ⋅         ⋅    ⋅     ⋅        ⋅           ⋅    ⋅    0.600465    ⋅ 
  ⋅         ⋅    ⋅     ⋅        ⋅           ⋅    ⋅     ⋅          ⋅ 
  ⋅         ⋅    ⋅     ⋅        ⋅           ⋅    ⋅   -0.694171    ⋅ 
  ⋅         ⋅    ⋅    0.13952   ⋅           ⋅    ⋅     ⋅          ⋅ 
  ⋅         ⋅    ⋅     ⋅        ⋅       …   ⋅    ⋅     ⋅         0.656815
 1.09027    ⋅    ⋅     ⋅        ⋅           ⋅    ⋅     ⋅        -1.44275
  ⋅         ⋅    ⋅     ⋅        ⋅           ⋅    ⋅     ⋅          ⋅ 
  ⋅         ⋅    ⋅   -1.31797  1.58432      ⋅    ⋅     ⋅          ⋅ 
 0.899571   ⋅    ⋅     ⋅        ⋅           ⋅    ⋅     ⋅        -0.647212

Question: why do we use `SparseArrays`?
- sparse matrix는 memory를 적게 차지함.
- nonzero elements의 value와 location index를 저장.
- 10개의 float과 20개의 정수만으로 10*10 matrix를 가리킬 수 있음. 저장공간 비교하면 30개 vs 100개.

In [66]:
# convert to dense matrix; be cautious when dealing with big data
Xfull = convert(Matrix{Float64}, X)

10×10 Matrix{Float64}:
 0.0       0.0  0.0   0.0      0.0      …  0.0  0.0   0.0        0.0
 0.0       0.0  0.0   0.0      0.0         0.0  0.0   0.600465   0.0
 0.0       0.0  0.0   0.0      0.0         0.0  0.0   0.0        0.0
 0.0       0.0  0.0   0.0      0.0         0.0  0.0  -0.694171   0.0
 0.0       0.0  0.0   0.13952  0.0         0.0  0.0   0.0        0.0
 0.0       0.0  0.0   0.0      0.0      …  0.0  0.0   0.0        0.656815
 1.09027   0.0  0.0   0.0      0.0         0.0  0.0   0.0       -1.44275
 0.0       0.0  0.0   0.0      0.0         0.0  0.0   0.0        0.0
 0.0       0.0  0.0  -1.31797  1.58432     0.0  0.0   0.0        0.0
 0.899571  0.0  0.0   0.0      0.0         0.0  0.0   0.0       -0.647212

In [67]:
# convert a dense matrix to sparse matrix
sparse(Xfull)

10×10 SparseMatrixCSC{Float64, Int64} with 11 stored entries:
  ⋅         ⋅    ⋅     ⋅        ⋅       …   ⋅    ⋅     ⋅          ⋅ 
  ⋅         ⋅    ⋅     ⋅        ⋅           ⋅    ⋅    0.600465    ⋅ 
  ⋅         ⋅    ⋅     ⋅        ⋅           ⋅    ⋅     ⋅          ⋅ 
  ⋅         ⋅    ⋅     ⋅        ⋅           ⋅    ⋅   -0.694171    ⋅ 
  ⋅         ⋅    ⋅    0.13952   ⋅           ⋅    ⋅     ⋅          ⋅ 
  ⋅         ⋅    ⋅     ⋅        ⋅       …   ⋅    ⋅     ⋅         0.656815
 1.09027    ⋅    ⋅     ⋅        ⋅           ⋅    ⋅     ⋅        -1.44275
  ⋅         ⋅    ⋅     ⋅        ⋅           ⋅    ⋅     ⋅          ⋅ 
  ⋅         ⋅    ⋅   -1.31797  1.58432      ⋅    ⋅     ⋅          ⋅ 
 0.899571   ⋅    ⋅     ⋅        ⋅           ⋅    ⋅     ⋅        -0.647212

In [68]:
# syntax for sparse linear algebra is the same as dense linear algebra
β = ones(10)
X * β

10-element Vector{Float64}:
  0.0
  0.6004651699162051
  0.0
 -0.6941713775369985
  0.13952013955757903
  0.6568146434250657
 -0.8489857271144514
  0.0
  0.26634788858336944
  0.25235898904879484

In [69]:
# many functions apply to sparse matrices as well
sum(X)

0.37234972587956405

## Control flow and loops

* if-elseif-else-end

```julia
if condition1
    # do something
elseif condition2
    # R에서는 else if
    # do something
else
    # do something
endb
```

* `for` loop

```julia
for i in 1:10
    println(i)
end
```

* Nested `for` loop:

```julia
for i in 1:10
    for j in 1:5
        println(i * j)
    end
end
```
Same as

```julia
for i in 1:10, j in 1:5
    println(i * j)
end
```

* Exit loop:

```julia
for i in 1:10
    # do something
    if condition1
        break # skip remaining loop
    end
end
```

* Exit iteration:  

```julia
for i in 1:10
    # do something
    if condition1
        continue # skip to next iteration
    end
    # do something
end
```

In [70]:
# Simple syntax for control flow equivalent to `ifelse` in R
# condition ? expression_if : expression_else

a=rand(5)
sum(a)<2 ? a=a+ones(Int, 5) : a=a-ones(Int, 5) ;
a

5-element Vector{Float64}:
 -0.03724229822297387
 -0.01445891373488739
 -0.2442234777868324
 -0.2458623931763093
 -0.18150611340336176

## Functions 

* Function definition
```julia
function func(req1, req2; key1=dflt1, key2=dflt2)
    # do stuff
    return out1, out2, out3
end
```
    - **Required arguments** are separated with a comma and use the positional notation.  
    - **Optional arguments** need a default value in the signature.  
    - **Semicolon** is not required in function call. It tells us that arguments after `;` are optional.
    - **return** statement is optional (value of the last expression is the return value, like R).  
    - Multiple outputs can be returned as a **tuple**, e.g., `return out1, out2, out3`.



* In Julia, all arguments to functions are [**passed by reference**](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_reference), in contrast to R and Matlab (which use pass by value).
    - Implication: function arguments can be **modified** inside the function.
    - If input refers to a mutable object then the object can be changed.
    
```julia
function f(x, y)
    return x+y
end
a = 10 ; b = 8
f(a,b)
```

* Observe what is going on when `f(a,b)` is implemented in the code above.
    - First, `x = a` and `y = b` are done. Does not create any copy. (Call by reference)
    - Then, calculates `x+y` and return it.
* On the other hand, if the same function is implemented in R, then
    - First, creates copies, `x<-a` and `y<-b` (Call by value), which is equivalent to `x=copy(a)` and `y=copy(b)` in Julia.
    - Then, calculates `x+y` and return it.
* Pros and Cons of "call by value" vs "call by reference"
    - Call by value : similar to mathematical expression in the sense that input value never changes when a function is applied.
    - Call by reference : Advantage in saving resources. In practical case, we sometimes wants to change the input value intentionally. However, if we don't want to modify the inputs, we should pay attention to it.



* By convention function names ending with `!` indicates that function mutates at least one argument, typically the first.

```julia
sort!(x) vs sort(x)
```

* Observe what is going on when `z = sort(x)` is implemented
    - First, `y = copy(x)` is done where "y" is a nominal varaible.
    - Second, somehow sorts elements of `y` and return `y`.
    - Fianlly, `z = copy(y)` is done. 
    - Creating a copy in the last step, instead of `z = y`, is due to the fact that inside of a function is a kind of "blackbox" so that we cannot refer to the object created inside of the function blackbox. 
    
* Now observe what is going on when `sort!(x)` is implemented
    - First, `y = x` is done where "y" is a nominal variable.
    - Next, somehow sorts elements of y. By doing this, `x` is also changed accordingly i.e. sorted.
* While `z = sort(x)` brings out two copies, `sort!(x)` does not create any copy.



In [71]:
# Compare `filter` vs `filter!`
x=collect(1:10)
y=filter(z->z>3, x)
x

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [72]:
filter!(z->z>3, x)
x

7-element Vector{Int64}:
  4
  5
  6
  7
  8
  9
 10

* There is a subtle binding issue (see the Indexing section above) in functions; see the "I passed an argument `x` to a function, modified it inside that function, but on the outside, the variable `x` is still unchanged. Why?" section of  https://docs.julialang.org/en/v1/manual/faq/

```julia
x = 10
function change_value!(y)
    y = 17
end
change_value!(x)   # result is 17
x     # result is 10, x is unchanged!

```

* The problem in the above code is clear when we look into what happens step by step.
    - At first, `x` points to an integer 10.
    - As `change_value!(x)` is implemented, `y = x` is done so that `y` also refers to an integer 10.
    - Then `y = 17` makes `y` refer to 17 and the binding between `y` and 10 be broken. This is because an integer 10 is immutable object. 
    - Obviously, `x` still refers to 10. 


```julia
x = [1,2,3]
function change_array!(A)
    A[1] = 5
    println("First element must be change into 5")
end
change_array!(x)    # The sentence above is printed.
x    # result is a vector (5,2,3) as expected.
```

* Here, the function has worked as we expected. Let's observe what happens.
    - At first, `x` points to a vector (1,2,3).
    - As `change_array!(x)` is implemented, `A = x` is done so that `A` also refers to a vector (1,2,3).
    - Then `A[1] = 5` makes the first element of the object referred to as "A" change into 5. (This is because the object referred to as "A" is mutable)
    - Now, both `A` and `x` refers to a modified vector (5,2,3). 
    - After function implementation is ended, `A` is left in the blackbox but still `x` refers to the vector (5,2,3)

* Anonymous functions, e.g., `x -> x^2`, is commonly used in collection function or list comprehensions.
```julia
map(x -> x^2, y) # square each element in x
# map(f, c, ...) transforms collection c by applying f to each element. For multiple collection arguments, apply f elementwise.
# e.g.   map(+, [1, 2, 3], [10, 20, 30])
```

* Functions can be nested:

```julia
function outerfunction()
    # do some outer stuff
    function innerfunction()
        # do inner stuff
        # can access prior outer definitions
    end
    # do more outer stuff
end
```

In this case, "innerfunction" is just left in the blackbox so that we cannot use it later. Only the "outerfunction" is allocated in the memory. 

* Functions can be vectorized using the "dot call" syntax:

In [73]:
function myfunc(x)
    return sin(x^2)
end

x = randn(5, 3)
myfunc.(x)

5×3 Matrix{Float64}:
 -0.966867   0.0174515    0.685276
  0.0173183  0.157789     0.13345
  0.201887   0.302368     0.846893
  0.926636   0.0122978   -0.571227
  0.150561   8.81735e-5   0.269939

* **Collection function** (think this as the series of `apply` functions in R).

    Apply a function to each element of a collection:

```julia
map(f, coll) # or
map(coll) do elem
    # do stuff with elem
    # must contain return
end
```

In [74]:
map(x -> sin(x^2), x)   # same as above

5×3 Matrix{Float64}:
 -0.966867   0.0174515    0.685276
  0.0173183  0.157789     0.13345
  0.201887   0.302368     0.846893
  0.926636   0.0122978   -0.571227
  0.150561   8.81735e-5   0.269939

In [75]:
map(x) do elem   # long version of above
    elem = elem^2
    return sin(elem)
end

5×3 Matrix{Float64}:
 -0.966867   0.0174515    0.685276
  0.0173183  0.157789     0.13345
  0.201887   0.302368     0.846893
  0.926636   0.0122978   -0.571227
  0.150561   8.81735e-5   0.269939

In [76]:
map(+, x, randn(5,3))

5×3 Matrix{Float64}:
  2.26931   -0.732447  -1.73343
  2.41791    0.111514   0.271391
 -0.600834   0.159821   1.50559
 -1.39056   -0.754271  -2.23943
  1.59671   -1.41553   -1.51074

In [77]:
# Mapslices
mapslices(sum, x, dims=1)

1×3 Matrix{Float64}:
 1.68309  0.0962185  -4.64325

In [78]:
mapslices(sum, x, dims=2)

5×1 Matrix{Float64}:
  0.6977508778702102
  0.8955146685284747
 -1.1084092196271638
 -3.2241416492810506
 -0.12465749614030763

In [79]:
# Mapreduce
mapreduce(x -> sin(x^2), +, x)   # mapreduce(mapper, reducer, data)
# Note :  any commutative operator can be used as reducer

2.1838603826843364

In [80]:
# same as
sum(x -> sin(x^2), x)

2.1838603826843364

* List **comprehension**

In [81]:
[sin(2i + j) for i in 1:5, j in 1:3] # similar to Python

5×3 Matrix{Float64}:
  0.14112   -0.756802  -0.958924
 -0.958924  -0.279415   0.656987
  0.656987   0.989358   0.412118
  0.412118  -0.544021  -0.99999
 -0.99999   -0.536573   0.420167

* Examples of creating functions

In [90]:
using Distributions
function jgibbs(N::Integer, thin::Integer)
    mat = Array{Float64}(undef, N, 2)
    x = y = 0.
    for i in 1:N
        for j in 1:thin
            x = rand(Gamma(3. , 1. /(y*y+4.))) 
            y = rand(Normal(1. /(x+1.) , 1. /sqrt(2. *(x+1.))))
        end
        mat[i,1] = x; mat[i,2] = y
    end
    return mat
end
##
jgibbs(10000,500)


10000×2 Matrix{Float64}:
 1.27711   -0.0125907
 0.557944   0.859622
 0.473635   0.908102
 1.63491   -0.162881
 0.489278   0.256862
 0.824462   0.466253
 0.521959   0.691617
 1.39269   -0.080664
 0.500461   1.51723
 0.630959  -0.441451
 0.40078    0.528136
 0.384678   0.950615
 0.205146   0.292238
 ⋮         
 0.900853   0.515373
 0.132944  -0.517094
 0.494853   0.814155
 0.704703   0.570945
 0.260682  -0.473381
 0.506734   0.689692
 0.53043    0.879789
 1.09878    0.88934
 1.34113    0.00400934
 1.41033    0.837123
 0.781796   0.205745
 0.358014   0.169364

In [91]:
@elapsed jgibbs(10000,500)

0.407948467

In [2]:
function sumsq(V::AbstractArray{<:Number})
    s = zero(typeof(V[1]))
    for v in V ; s +=v*v ; end
    return s
end
sumsq(collect(1:5))


55

In [3]:
char=["a", "b", "c"];
sumsq(char)

LoadError: MethodError: no method matching sumsq(::Vector{String})
Closest candidates are:
  sumsq(::AbstractArray{var"#s28", N} where {var"#s28"<:Number, N}) at In[2]:1

In [2]:
function matprod(A::AbstractArray{<:Number}, B::AbstractArray{<:Number})
    m,n = size(A); p,q = size(B)
    n == p || error("Input error : Incompatible dimensions")
    A*B
end
A=rand(5,3)
B=rand(3,2)
matprod(A,B)

5×2 Matrix{Float64}:
 0.911552  1.39091
 0.28008   0.503826
 0.730772  0.977696
 1.24585   1.66537
 1.18484   1.49138

In [98]:
C=rand(2,2)
matprod(A,C)

LoadError: Input error : Incompatible dimensions

In [5]:
logit(p::Real) = 0 < p < 1 ? log(p/(1-p)) : 
error("input of logit function should be p in (0,1)")
logit(3) 

LoadError: input of logit function should be p in (0,1)

In [6]:
logit(0.5)

0.0

In [8]:
logit(V::AbstractArray{<:Real})=[logit(v) for v in V]
a=collect(LinRange(0.1, 0.9, 9));
logit(a)

9-element Vector{Float64}:
 -2.197224577336219
 -1.3862943611198906
 -0.8472978603872034
 -0.4054651081081643
  0.0
  0.4054651081081642
  0.8472978603872039
  1.3862943611198901
  2.1972245773362196

In [82]:
function backfit(X::Matrix, y::Vector; h::Float64=0.5, nIter::Int64=20)
    n,p=size(X)
    length(y)==n || error("Dimension mismatch between input X and y")
    e0=randn(n)
    lambda=p*(1-h)/h
    SSx=sum(X.^2, dims=1)
    beta=zeros(p)
    e=copy(e0)
    for i in 1:nIter
        for j in 1:p
            yStar=e+X[:,j]*beta[j]
            beta[j]=X[:,j]'yStar/(SSx[j]+lambda)
            e=yStar-X[:,j]*beta[j]
        end
    end
    return beta
end

n=3; p=5;

beta_true = collect(1:(p+1))
X= [ones(n) randn(n,p)]
y= randn(n)+X*beta_true
b=backfit(X, y, nIter=10000)
# Thanks to semicolon in the definition of `backfit` for the keywords, we can use keyword argument "nIter=1000"

6-element Vector{Float64}:
 -0.004913072700790791
  0.012151449630744384
 -0.013475443447653316
  0.004402028709594102
  0.0021824485724188957
 -0.009715607626059115

## Type system

* Every variable in Julia has a type.

* R이나 Python과 달리 variable의 type이 반드시 정해져야 하고, 안 정해지면 any라는 type으로 설정된다.

* When thinking about types, think about sets.

* Everything is a subtype of the abstract type `Any`.

* An abstract type defines a set of types
    - Consider types in Julia that are a `Number`:
<img src="./images/Julia-number-type-hierarchy.svg" width="800" align="center"/>
    - source: https://en.wikibooks.org/wiki/Introducing_Julia/Types

Int16 또는 Float64의 숫자는 precision에 대한 것임.

* We can explore type hierarchy with `typeof()`, `supertype()`, and `subtypes()`.

In [83]:
typeof(1.0), typeof(1)

(Float64, Int64)

In [84]:
supertype(Float64)

AbstractFloat

In [85]:
subtypes(AbstractFloat)

4-element Vector{Any}:
 BigFloat
 Float16
 Float32
 Float64

In [91]:
# Is Float64 a subtype of AbstractFloat?
Float64 <: AbstractFloat

true

In [92]:
# On 64bit machine, Int == Int64
Int == Int64

true

In [93]:
# convert to Float64
convert(Float64, 1)

1.0

In [94]:
# same as
Float64(1)

1.0

In [95]:
# Float32 vector
x = randn(Float32, 5)

5-element Vector{Float32}:
 -0.84469885
  0.45394865
  0.17271501
 -1.5224358
  1.3761741

In [96]:
# convert to Float64
convert(Array{Float64}, x)

5-element Vector{Float64}:
 -0.8446988463401794
  0.45394864678382874
  0.17271500825881958
 -1.5224357843399048
  1.3761740922927856

In [97]:
# same as
Float64.(x)

5-element Vector{Float64}:
 -0.8446988463401794
  0.45394864678382874
  0.17271500825881958
 -1.5224357843399048
  1.3761740922927856

In [98]:
# convert Float64 to Int64
convert(Int, 1.0)

1

In [99]:
convert(Int, 1.5) # should use round(1.5)

LoadError: InexactError: Int64(1.5)

In [100]:
round(Int, 1.5)

2

## Multiple dispatch

* [Multiple dispatch](https://en.wikipedia.org/wiki/Multiple_dispatch) is a feature of some programming languages in which a function or method can be dynamically dispatched based on the run time (dynamic) type or, in the more general case, some other attribute of more than one of its arguments.

* Multiple dispatch lies in the core of Julia design. It allows built-in and user-defined functions to be overloaded for different combinations of argument types.

* In Juila, methods belong to functions, called **generic functions**.

* Let's consider a simple "doubling" function:

In [128]:
g(x) = x + x
# R에서도 함수 작성 시 input argument의 type을 규정할 필요 없었음. 적절한 type의 input이 들어오지 않으면 이상한 결과가 나올 뿐임.

g (generic function with 3 methods)

In [104]:
g(1.5)

3.0

This definition is too broad, since some things, e.g., strings, can't be added 

In [129]:
g("hello world")

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560

* This definition is correct but too restrictive, since any `Number` can be added.

In [130]:
g(x::Float64) = x + x
# Now function g has 2 methods. "function and method are different notion"

g (generic function with 3 methods)

* This definition will automatically work on the entire type tree above!

In [131]:
g(x::Number) = x + x

g (generic function with 3 methods)

This is a lot nicer than 
```julia
function g(x)
    if isa(x, Number)  # `isa(x, type)` determines whether x is of the given type
        return x + x
    else
        throw(ArgumentError("x should be a number"))
    end
end
```

* `methods(func)` function display all methods defined for `func`.

In [110]:
methods(g)

# 3 methods for generic function "g":
[1] g(x::Float64) in Main at In[106]:1
[2] g(x::Number) in Main at In[108]:1
[3] g(x) in Main at In[103]:1

* When calling a function with multiple definitions, Julia will search from the *narrowest* signature to the broadest signature.

* `@which func(x)` marco tells which method is being used for argument signature `x`.

In [113]:
# an Int64 input
@which g(1)

g(x::Number) in Main at In[108]:1

In [114]:
@which g(1.0)

g(x::Float64) in Main at In[106]:1

In [80]:
# a Vector{Float64} input
@which g(randn(5))

g(x) in Main at In[72]:1

* R also makes use of generic functions and multiple dispatch (see http://adv-r.had.co.nz/OO-essentials.html#s3), but it is not fully optimized.

## Just-in-time compilation (JIT)

| <img src="./images/julia_toolchain.png" alt="Julia toolchain" style="width: 400px;"/> | <img src="./images/julia_introspect.png" alt="Julia toolchain" style="width: 500px;"/> |
|----------------------------------|------------------------------------|
|||

Source: [Introduction to Writing High Performance Julia](https://youtu.be/szE4txAD8mk) by Arch D. Robinson

* `Julia`'s efficiency results from its capability to infer the types of **all** variables within a function and then call LLVM (compiler) to generate optimized machine code at run-time. 

Consider the `g` (doubling) function defined earlier. This function will work on **any** type which has a method for `+`.

In [132]:
g(2), g(2.0)
# 두 개의 method 모두 이미 compile 된 상태

(4, 4.0)

**Step 1**: Parse Julia code into [abstract syntax tree (AST)](https://en.wikipedia.org/wiki/Abstract_syntax_tree).

In [133]:
@code_lowered g(2)
# 문법 요소 별로 분해해서 syntax tree를 만든다.
# 두 단계로 코드 분해    1. nominal variable에 x+x를 저장   2. 해당 variable을 return 

CodeInfo(
1 ─ %1 = x + x
└──      return %1
)

**Step 2**: Type inference according to input type.

In [134]:
@code_warntype g(2)
# infer the type of nominal variable according to input data type

Variables
  #self#::Core.Const(g)
  x::Int64

Body::Int64
1 ─ %1 = (x + x)::Int64
└──      return %1


In [135]:
@code_warntype g(2.0)

Variables
  #self#::Core.Const(g)
  x::Float64

Body::Float64
1 ─ %1 = (x + x)::Float64
└──      return %1


**Step 3**: Compile into **LLVM bytecode** (equivalent of R bytecode generated by the compiler package).

In [124]:
@code_llvm g(2)
# `i64` refers to int64
# `shl` refers to shiftleft
# 이진법에서 1000->10000 되는 것이 십진법에서는 두 배와 동일.

;  @ In[108]:1 within `g'
define i64 @julia_g_4804(i64 signext %0) {
top:
; ┌ @ int.jl:87 within `+'
   %1 = shl i64 %0, 1
; └
  ret i64 %1
}


In [123]:
@code_llvm g(2.0)
# `fadd` refers to float adding

;  @ In[106]:1 within `g'
define double @julia_g_4802(double %0) {
top:
; ┌ @ float.jl:326 within `+'
   %1 = fadd double %0, %0
; └
  ret double %1
}


We didn't provide a type annotation. But different LLVM code gets generated depending on the argument type!

In R or Python, `g(2)` and `g(2.0)` would use the same code for both.
 
In Julia, `g(2)` and `g(2.0)` dispatches to optimized code for `Int64` and `Float64`, respectively.

For integer input `x`, LLVM compiler is smart enough to know `x + x` is simple shifting `x` by 1 bit, which is faster than addition.
 
* **Step 4**: Lowest level is the **assembly code**, which is machine dependent.  

Note that LLVM code is not dependent on machine


In [126]:
@code_native g(2)

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ In[108]:1 within `g'
; │┌ @ int.jl:87 within `+'
	leaq	(%rdi,%rdi), %rax
; │└
	retq
	nopw	%cs:(%rax,%rax)
; └


1st instruction adds the content of the general purpose 64-bit register (a small memory inside the CPU) RDI to itself, and load the result into another register RAX. The addition here is the integer arithmetic.

In [127]:
@code_native g(2.0)

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ In[106]:1 within `g'
; │┌ @ float.jl:326 within `+'
	vaddsd	%xmm0, %xmm0, %xmm0
; │└
	retq
	nopw	%cs:(%rax,%rax)
; └


1st instruction adds the content of the 128-bit register XMM0 to itself, and overwrites the result into XMM0. The addition here is the floating point arithmetic and a "single instruction, multiple data" (SIMD) instruction.

## Acknowledgment

This lecture note has evolved from [Dr. Hua Zhou](http://hua-zhou.github.io)'s 2019 Winter Statistical Computing course notes available at <http://hua-zhou.github.io/teaching/biostatm280-2019spring/index.html>.